version: '3.7'
volumes:
  postgres_data:
    external: true

services:
  postgres-events:
      build:
        context: ./docker-files
        dockerfile: Dockerfile.postgres
      environment:
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_USER=event
          - POSTGRES_DB=events
      restart: always
      networks:
          - db-network
      ports:
          - "5432:5432"
      volumes:
          - postgres_data:/var/lib/postgresql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
    db-network:
        driver: bridge
