server:
  port: 8000
# endpoints are disabled by default
# management.endpoints.web.exposure.include=prometheus
# management.metrics.tags.application=${spring.application.name}
# Disable lazy loading for this app
spring:
  application:
    name: events-server
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/events
    username: event_app
    password: event_app
    driverClassName: org.postgresql.Driver
opentracing:
  jaeger:
    log-spans: true
    service-name: events-server
    enabled: false
    udp-sender:
       host: "jaeger"
management:
  info:
    git:
      mode: full
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    beans:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
      tags:
        application: ${spring.application.name}
    httptrace:
      enabled: true
    env:
      enabled: true
fake-key: my-properties-google-key
